name: cbmapn
channels:
  - conda-forge
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.17.2=pyhd8ed1ab_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - colorlog=6.10.1=pyh707e725_0
  - greenlet=3.2.4=py310hea6c23e_1
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ld_impl_linux-64=2.45=h1aa0949_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - mako=1.3.10=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - optuna=4.6.0=pyhd8ed1ab_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sqlalchemy=2.0.44=py310h7c4b9e2_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - astor==0.8.1
      - blis==1.3.2
      - catalogue==2.0.10
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.12
      - decorator==5.2.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gast==0.6.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - murmurhash==1.0.15
      - networkx==3.4.2
      - nltk==3.9.2
      - nose==1.3.7
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - plac==1.4.5
      - preshed==3.0.11
      - protobuf==6.33.1
      - pycurl==7.45.7
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - six==1.17.0
      - smart-open==7.5.0
      - spacy==3.8.9
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - thinc==8.3.9
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - werkzeug==3.1.3
      - wrapt==2.0.1
prefix: /home/sb76faku/.conda/envs/cbmapn
